theme: jekyll-theme-hacker
title: iRacing Reports Discord Bot
description: A Discord bot that allows users to access a range of statistical information about iRacing Drivers, Championships, and Series
navigation:
  - title: Home
    url: /
  - title: User Guide
    url: https://iracingreports.com/static/iRacing_Reports_bot_commands.pdf
  - title: Screenshots
    url: /screenshots
  - title: Demo Video
    url: /demo_video
  - title: Our Discord
    url: /discord
  - title: Dev Log
    url: /devlog
github:
  is_project_page: false
  